project:
  type: website

website:
  title: "Alexander"
  site-url: "https:://awchen55.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts
        text: blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

